### ISSUE TITLE
using gist to submit the excercise (as bonus)

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/Scripting4GeoIntro#5]
https://gist.github.com/hadley/270442

It would be nice if we can add a short link for students how to create gists so that they can provide their exercise as a gist in blackboard

**Comment by GreatEmerald** [comment]
Added this as a protip to pull #7.

**Comment by janverbesselt** [comment]
Nice - and I would agree with the suggestion of using Gitlab - maybe that is even better:
https://git.wur.nl/snippets/new

**Comment by GreatEmerald** [comment]
The problem with GitLab is that it's not clear to me how they implement permissions. It seems that they use the same permissions as for regular projects (Public/Internal/Private), but in this case we want something they could paste as a link that would not be otherwise searchable, which is the concept of secret gists.
